// SlotWiki Data — all content pulled from provider source data
// Merged from hacksaw_slots and Final Hacksaw Slot upload code spreadsheets

const PROVIDERS = [
  {
    id: "hacksaw",
    name: "Hacksaw Gaming",
    slug: "hacksaw",
    website: "https://www.hacksawgaming.com",
    logo: "https://www-live.hacksawgaming.com/casino_thumbnails/2274_logo_Logo_800width.png",
    score: "9.2",
    description:
      "Hacksaw Gaming is an innovative slots and scratch card provider known for high-energy gameplay, bold visual design, and player-first mechanics. Founded in 2018, they have quickly built a reputation for delivering cinematic slot experiences with features like DuelReels, LootLine wins, and Hold & Win mechanics. Every game pushes the boundary between storytelling and gameplay.",
    featured: true,
  },
  {
    id: "pragmatic",
    name: "Pragmatic Play",
    slug: "pragmatic",
    website: "https://www.pragmaticplay.com",
    logo: null,
    score: "9.4",
    description:
      "Pragmatic Play is one of the world's leading content providers to the iGaming industry, delivering top-quality products across slots, live casino, bingo, and more. Known for iconic titles like Sweet Bonanza, Gates of Olympus, Big Bass Bonanza and Starlight Princess, Pragmatic consistently sets the standard for player engagement and innovative mechanics including Megaways, tumble features, and multiplier wilds.",
    featured: true,
  },
];

// TAG_RULES: [display tag, [...keywords checked against lower-cased name+tagline]]
const TAG_RULES = [
  ["Horror", ["hell", "cursed", "demon", "undead", "evil", "crypt", "nightmare", "beast", "vampire", "devil", "darkness", "twisted", "six six", "666"]],
  ["Greek Mythology", ["zeus", "athena", "hercules", "medusa", "ares", "olympus", "gorgon", "perseus", "horus"]],
  ["Egypt", ["egypt", "pharaoh", "nile", "pyramid", "scarab", "sand and ashes", "wings of horus", "desert"]],
  ["Pirates", ["pirate", "ship", "sail", "anne bonny", "galleon", "davy jones", "bounty"]],
  ["Fantasy", ["dragon", "princess", "magic", "wizard", "enchanted", "spirit", "fairy", "sorcerer", "myth", "legend", "phoenix"]],
  ["Wild West", ["cowboy", "west", "outlaw", "gunslinger", "duel", "bandit", "saddle", "quick draw", "sheriff"]],
  ["Norse", ["viking", "norse", "ymir", "ragnarok", "stormborn", "valhalla", "thor"]],
  ["Underwater", ["ocean", "sea", "fish", "deep", "octopus", "atlantis", "marlin", "aqua", "breath"]],
  ["Animals", ["tiger", "bunny", "toad", "octopus", "hound", "monkey", "pig", "piggy", "banana", "dragon"]],
  ["Food & Sweets", ["candy", "food", "donut", "cheese", "banana", "jelly", "munch", "truck", "slice"]],
  ["Sci-Fi", ["space", "laser", "galaxy", "planet", "alien", "steampunk", "steam", "airship"]],
  ["Roman", ["rome", "roman", "gladiator", "caesar", "legion"]],
  ["Asian", ["shaolin", "toshi", "aiko", "tai the toad", "wind spirit", "martial"]],
  ["Christmas", ["santa", "christmas", "xmas", "festive"]],
  ["Crime & Heist", ["crime", "heist", "crew", "miami", "mafia", "gang", "cop"]],
  ["Clowns", ["clown", "circus", "klown", "funhouse"]],
  ["Rodents", ["mouse", "rat", "cheese", "rodent", "trap", "get the cheese"]],
  ["Fishing", ["marlin", "fishing", "reel in", "catch", "angler", "fisherman", "cast"]],
  ["Luxury", ["luxe", "luxury", "vip", "opulence", "champagne", "tux"]],
  ["Combat", ["fighter", "fight", "battle", "warrior", "combat", "arena", "gladiator", "slayer", "kill", "slay"]],
  ["Gems & Jewels", ["gem", "jewel", "diamond", "crystal", "ruby", "sapphire", "emerald"]],
  ["Megaways", ["megaways"]],
  ["Bonanza", ["bonanza"]],
  ["Aztec", ["aztec", "inca", "mayan"]],
  ["Irish", ["irish", "clover", "leprechaun", "shamrock"]],
  ["Wolf & Wildlife", ["wolf", "bear", "wildebeest", "stampede", "safari", "savannah"]],
  ["Zombie", ["zombie", "undead", "ghoul", "dead"]],
  ["Magic & Spells", ["magic", "witch", "spell", "wizard", "genie", "potion", "mystic"]],
];

function getTags(slot) {
  const hay = (slot.name + " " + slot.tagline).toLowerCase();
  return TAG_RULES.filter(([, kws]) => kws.some((kw) => hay.includes(kw))).map(([tag]) => tag);
}

// Merge of both spreadsheets. Slots with game_id have CDN thumbnails.
// thumbnail_url null = no image available (newer unreleased titles)
const RAW_SLOTS = [
  // — With game IDs (CDN images available) —
  { game_id: 2274, name: "Red Rascal", slug: "red-rascal", rtp: "96.34%", max_win: "15,000x", release_date: "May 21st 2026", tagline: "GET READY TO RIOT! Is this a portal to hell or just the devil's playground? It's hard to tell because a devilish rascal has taken over this funhouse. Full of evil clowns, where even the rides run wild. He's been let loose and is ready to burn it all down. But in his defence, the moon is full and he was left unsupervised.", bonus_buy_rtps: ["94.29%", "92.26%", "86.35%"], features: [], bonus_games: [], featured: true },
  { game_id: 2213, name: "Rise of Fortuna", slug: "rise-of-fortuna", rtp: null, max_win: null, release_date: null, tagline: "They Call her the Lady of Luck! Fortuna Wheels spin with additive and multiplicative multipliers while the Cash Prize Bar collects your rewards.", features: [{title:"FORTUNA WHEELS",description:"Regular, Super and Epic Fortuna Wheels are triggered when a Fortuna symbol lands on the grid."},{title:"CASH PRIZE BAR",description:"The Cash Prize Bar collects values from each Wheel and rewards a final cash prize as a multiple of your bet."}], bonus_games: [{title:"LUCKY CHARM",description:"Land 3 FS scatter symbols — 10 free spins with higher Fortuna Wheel chance."},{title:"SHE WHO SPINS",description:"Land 4 FS scatter symbols — 10 free spins where all Fortuna Wheels are Super or Epic."},{title:"GOLDEN GODDESS",description:"Land 5 FS scatter symbols — unlimited free spins where all Fortuna Wheels are Epic."}], featured: true },
  { game_id: 2243, name: "Sand and Ashes", slug: "sand-and-ashes", rtp: "96.27%", max_win: "10,000x", release_date: "May 14th 2026", tagline: "Defend the Nile — Claim the Glory! With the heart of a lion, the warden of the sands has one mission left before going to eternal rest. A threat to the realm is revealing itself on the horizon.", bonus_buy_rtps: ["94.07%", "96.10%", "95.60%"], features: [{title:"WILD SCARAB MULTIPLIERS",description:"Wild Scarab Multipliers trigger a respin with a multiplier value of up to 200x. Respins continue until no new Wilds land."},{title:"FIRESTORMS AND SANDSTORMS",description:"During respins a Firestorm increases all Wild Multipliers, while a Sandstorm nudges all symbols one reel to the left."}], bonus_games: [{title:"FREE SPINS",description:"Land 3 Scatter Bonus symbols — 10 free spins locked in the active round type."}], featured: true },
  { game_id: 2219, name: "Munchy Milo", slug: "munchy-milo", rtp: null, max_win: null, release_date: null, tagline: "READY, SET, MUNCH! Meet Milo — the most eccentric, candy-obsessed slot character this side of Candy Land! He's bouncing off the walls literally as he devours every sweet treat in sight.", features: [], bonus_games: [{title:"LIFT OFF LUCK",description:"Keeps base game mechanics with increased Jolt Frame chances."},{title:"GRAVITY GROOVE",description:"Wild symbols with multipliers become Sticky until bonus end."},{title:"GOING BANANAS",description:"1 Jolt Frame guaranteed on every spin!"}], featured: false },
  { game_id: 2296, name: "3 Cursed Chests: Hold & Win", slug: "3-cursed-chests-hold-win", rtp: "96.30%", max_win: "2,500x", release_date: "May 28th 2026", tagline: "Set sail with Anne Bonny and her ship! Cursed be the gold, a fortune long foretold. When the tides turn, the sails will burn.", bonus_buy_rtps: ["94.37%", "92.30%", "86.29%"], features: [], bonus_games: [{title:"GHOSTLY GALLOWS",description:"Trigger the Cursed FS and land FS + a FS Upgrade symbol for 7–15 free spins where landing a Pot symbol guarantees the matching Chest activates."}], featured: true },
  { game_id: 2258, name: "Magic Piggy OG", slug: "magic-piggy-og", rtp: "96.20%", max_win: "2,500x", release_date: "May 5th 2026", tagline: "Feel the Piggy Power! Prepare to be enchanted by the magic of pigs with an OG grid!", features: [], bonus_games: [], featured: true },
  { game_id: 2195, name: "Le Bunny", slug: "le-bunny", rtp: null, max_win: null, release_date: null, tagline: "Smokey is back and the master of disguise keeps living up to his name!", features: [], bonus_games: [], featured: false },
  { game_id: 2234, name: "Power of Ten", slug: "power-of-ten", rtp: null, max_win: null, release_date: null, tagline: "Step into the salon and enter the exciting world of Power of Ten — where ten power wheels spin up multiplied fortunes.", features: [{title:"WHOPPING WHEELS",description:"Activate with 4 FS scatters — Power Wheels become sticky and build multipliers across the bonus."}], bonus_games: [], featured: false },
  { game_id: 2185, name: "Epic Bullets and Bounty", slug: "epic-bullets-and-bounty", rtp: null, max_win: null, release_date: null, tagline: "Saddle up and ride out — the most epic bounty hunt in the Wild West starts now.", features: [], bonus_games: [], featured: false },
  { game_id: 2082, name: "Dynasty of Death", slug: "dynasty-of-death", rtp: null, max_win: null, release_date: null, tagline: "Join the King and Queen of the Underworld as they go head-to-head in a dynasty battle for the ages.", features: [], bonus_games: [], featured: false },
  { game_id: 2108, name: "Marlin Masters Atlantis", slug: "marlin-masters-atlantis", rtp: null, max_win: null, release_date: null, tagline: "Take a deep breath and reel in the big one — the lost city of Atlantis is teeming with legendary catches.", features: [], bonus_games: [], featured: false },
  { game_id: 2115, name: "Pray for Six", slug: "pray-for-six", rtp: null, max_win: null, release_date: null, tagline: "It looks like someone left Hell's nursery gates open — and the chaos has spilled onto the reels.", features: [], bonus_games: [], featured: false },
  { game_id: 2143, name: "Dark Spiral", slug: "dark-spiral", rtp: null, max_win: null, release_date: null, tagline: "The girls scream within, as their reflections smile on from the outside. Descend into the Dark Spiral.", features: [], bonus_games: [], featured: false },
  { game_id: 2077, name: "Zeus Ze Zecond", slug: "zeus-ze-zecond", rtp: null, max_win: null, release_date: null, tagline: "Stand with the god of gods in Zeus Ze Zecond! Lightning bolts and divine multipliers return for round two.", features: [], bonus_games: [], featured: false },
  { game_id: 2148, name: "Eternal Duel", slug: "eternal-duel", rtp: null, max_win: null, release_date: null, tagline: "Two Brothers. Two Realms. One Destiny. The eternal duel has begun across the reels of fate.", features: [], bonus_games: [], featured: false },
  { game_id: 2229, name: "Le Digger", slug: "le-digger", rtp: null, max_win: null, release_date: null, tagline: "RAIDER OF RICHES — Le Digger is armed with a pickaxe and an unquenchable thirst for buried treasure.", features: [], bonus_games: [], featured: false },
  { game_id: 2190, name: "Dusk Princess", slug: "dusk-princess", rtp: null, max_win: null, release_date: null, tagline: "Princess Luna, keeper of shadows, draped in twilight silk, guides the constellations to their nocturnal home. Max win of 10,000×.", features: [], bonus_games: [], featured: false },
  { game_id: 2019, name: "Circle of Life", slug: "circle-of-life", rtp: null, max_win: null, release_date: null, tagline: "In the Circle of Life we fall, we fade, and we flower again. The eternal cycle spins on.", features: [], bonus_games: [], featured: false },
  { game_id: 1971, name: "Toshi Ways Club", slug: "toshi-ways-club", rtp: null, max_win: null, release_date: null, tagline: "Hack your way into Toshi Ways Club — the most exclusive members-only slot in the universe.", features: [], bonus_games: [], featured: false },
  { game_id: 2000, name: "Deal With Death", slug: "deal-with-death", rtp: null, max_win: null, release_date: null, tagline: "Deal With Death Itself. In the ultimate gamble, can you outwit the Grim Reaper?", features: [], bonus_games: [], featured: false },
  { game_id: 1965, name: "Le Santa", slug: "le-santa", rtp: null, max_win: null, release_date: null, tagline: "When Smokey Stole Christmas — Le Santa brings a sack full of wild spins and festive multipliers.", features: [], bonus_games: [], featured: false },
  { game_id: 1977, name: "Army of Ares", slug: "army-of-ares", rtp: null, max_win: null, release_date: null, tagline: "He's here — Ares, the god of war. March into battle and conquer the reels for legendary war spoils.", features: [], bonus_games: [], featured: false },
  { game_id: 2138, name: "Superstar Sevens", slug: "superstar-sevens", rtp: null, max_win: null, release_date: null, tagline: "Lightning Strikes! Lucky 7s shine brighter than ever in this superstar edition.", features: [], bonus_games: [], featured: false },
  { game_id: 1871, name: "Steamrunners", slug: "steamrunners", rtp: null, max_win: null, release_date: null, tagline: "The skies belong to us! The Steamrunners own the air — fierce, fearless, and wired for rebellion across floating steampunk cities.", features: [], bonus_games: [], featured: false },
  { game_id: 2062, name: "Hot Ross", slug: "hot-ross", rtp: null, max_win: null, release_date: null, tagline: "This just got real hot! Hot Ross is turning up the heat on the reels with scorching wilds and blazing bonuses.", features: [], bonus_games: [], featured: false },
  { game_id: 1914, name: "Sun Princess", slug: "sun-princess", rtp: null, max_win: null, release_date: null, tagline: "Sail the solar rays in Sun Princess — a radiant goddess of the sun reigns over the golden reels.", features: [], bonus_games: [], featured: false },
  { game_id: 1803, name: "The Count", slug: "the-count", rtp: null, max_win: null, release_date: null, tagline: "Welcome to The Count's castle — where the night is alive and the creatures are not!", features: [], bonus_games: [], featured: false },
  { game_id: 2004, name: "Donny and Danny", slug: "donny-and-danny", rtp: null, max_win: null, release_date: null, tagline: "Behind this curtain, witness something you've never seen before — Donny and Danny, the ultimate dynamic duo.", features: [], bonus_games: [], featured: false },
  { game_id: 1938, name: "Spear of Athena", slug: "spear-of-athena", rtp: null, max_win: null, release_date: null, tagline: "Goddess of Wisdom and War — Athena has chosen you to wield her legendary spear and claim the divine spoils of Olympus.", features: [], bonus_games: [], featured: false },
  { game_id: 2057, name: "Le Fisherman", slug: "le-fisherman", rtp: null, max_win: null, release_date: null, tagline: "Smokey on the water — Le Fisherman has found the perfect spot and is ready to reel in the catch of a lifetime.", features: [], bonus_games: [], featured: false },
  { game_id: 1924, name: "Le Cowboy", slug: "le-cowboy", rtp: null, max_win: null, release_date: null, tagline: "The Bandit has entered his Cowboy era — saddle up with Smokey Le Cowboy and ride into the sunset for riches.", features: [], bonus_games: [], featured: false },
  { game_id: 1830, name: "Le Zeus", slug: "le-zeus", rtp: null, max_win: null, release_date: null, tagline: "Armed with lightning — Le Zeus brings all the power of Mount Olympus to the reels.", features: [], bonus_games: [], featured: false },
  { game_id: 1875, name: "Stormborn", slug: "stormborn", rtp: null, max_win: null, release_date: null, tagline: "Step into the myth — Stormborn, a warrior forged in the fires of lightning and thunder, rides the storm to legendary treasure.", features: [], bonus_games: [], featured: false },
  { game_id: 1744, name: "Tiger Legends", slug: "tiger-legends", rtp: null, max_win: null, release_date: null, tagline: "Enter a world of ancient combat! Four fierce warriors rise in a land where legends are carved into stone and destinies forged in the dojo.", features: [], bonus_games: [], featured: false },
  { game_id: 1928, name: "Bash Bros", slug: "bash-bros", rtp: null, max_win: null, release_date: null, tagline: "THE BASHING BROS are here to smash, crash, and bash their way through the reels.", features: [], bonus_games: [], featured: false },
  { game_id: 1981, name: "Smoking Dragon", slug: "smoking-dragon", rtp: null, max_win: null, release_date: null, tagline: "Awakened from his long slumber, the Smoking Dragon has taken back the skies — and the treasure with it.", features: [], bonus_games: [], featured: false },
  { game_id: 1867, name: "Chaos Crew 3", slug: "chaos-crew-3", rtp: null, max_win: null, release_date: null, tagline: "The Chaos Crew is back — and they're more chaotic than ever for their third outing.", features: [], bonus_games: [], featured: false },
  { game_id: 1787, name: "Le King", slug: "le-king", rtp: null, max_win: null, release_date: null, tagline: "Smokey's back, and this time, he's playing for keeps! All hail Le King — ruler of the reels.", features: [], bonus_games: [], featured: false },
  { game_id: 1897, name: "The Luxe", slug: "the-luxe", rtp: null, max_win: null, release_date: null, tagline: "Welcome to The Luxe — where fortune wears a tux. Designer wins, VIP bonuses, and champagne jackpots await.", features: [], bonus_games: [], featured: false },
  { game_id: 1946, name: "Jaws of Justice", slug: "jaws-of-justice", rtp: null, max_win: null, release_date: null, tagline: "Conquer the cosmos — Jaws of Justice, where justice has teeth and the criminal jackpot is yours to crack open.", features: [], bonus_games: [], featured: false },
  { game_id: 1799, name: "Bullets and Bounty", slug: "bullets-and-bounty", rtp: null, max_win: null, release_date: null, tagline: "Quick draw shootout! Saddle up and ride out with Quick Draw Kate in Bullets and Bounty. Max win up to 20,000×.", features: [], bonus_games: [], featured: false },
  { game_id: 1824, name: "Miami Mayhem", slug: "miami-mayhem", rtp: null, max_win: null, release_date: null, tagline: "Team up for the score of a lifetime! Sun, sand, and slot machines — Miami Mayhem where the neon never stops burning.", features: [], bonus_games: [], featured: false },
  { game_id: 1783, name: "Booze Bash", slug: "booze-bash", rtp: null, max_win: null, release_date: null, tagline: "Sweet Taste of Mischief! The Booze Bash is the wildest party in slot history — drinks flowing, music pumping.", features: [], bonus_games: [], featured: false },
  { game_id: 1756, name: "Aiko and the Wind Spirit", slug: "aiko-and-the-wind-spirit", rtp: null, max_win: null, release_date: null, tagline: "Guided by the whispering wind — young Aiko soars through enchanted lands with the Wind Spirit at her side.", features: [], bonus_games: [], featured: false },
  { game_id: 1791, name: "Invictus", slug: "invictus", rtp: null, max_win: null, release_date: null, tagline: "No mercy — only eternal glory. The spirit of Invictus cannot be broken. Face the reels with the heart of a champion.", features: [], bonus_games: [], featured: false },
  { game_id: 1229, name: "Freds Food Truck", slug: "freds-food-truck", rtp: null, max_win: null, release_date: null, tagline: "The orders are in — Fred's Food Truck is ready to spin! The most legendary food truck in the land serves up wins.", features: [], bonus_games: [], featured: false },
  { game_id: 1891, name: "The Wildwood Curse", slug: "the-wildwood-curse", rtp: null, max_win: null, release_date: null, tagline: "Three went into the woods. None came back the same. Beware the Wildwood Curse.", features: [], bonus_games: [], featured: false },
  { game_id: 1740, name: "Eye of Medusa", slug: "eye-of-medusa", rtp: null, max_win: null, release_date: null, tagline: "Perseus, sword in hand, stepped into the shadowy lair of Medusa. Eye of Medusa invites you on this mythic quest. Max win 10,000×.", features: [], bonus_games: [], featured: false },
  { game_id: 1811, name: "Marlin Masters: The Big Haul", slug: "marlin-masters-the-big-haul", rtp: null, max_win: null, release_date: null, tagline: "The elusive Marlin has been spotted off the coast — will today be the day you reel in the Big Haul? Max win 10,000×.", features: [], bonus_games: [], featured: false },
  { game_id: 1817, name: "Rainbow Princess", slug: "rainbow-princess", rtp: null, max_win: null, release_date: null, tagline: "Born from stardust and empowered by gems — the Rainbow Princess rules over a magical realm of colour and fortune.", features: [], bonus_games: [], featured: false },
  // — No game IDs (unreleased / not yet on CDN) —
  { game_id: null, name: "Ultimate Slot Of America", slug: "ultimate-slot-of-america", rtp: null, max_win: null, release_date: null, tagline: "Stars, stripes, and spinning reels — this is the slot that embodies the spirit of America. Big wins, big dreams, the ultimate jackpot.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Spinman", slug: "spinman", rtp: null, max_win: null, release_date: null, tagline: "In a world where only spins can save humanity, one hero rises. Spinman — the reel superhero you never knew you needed.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Pray For Three", slug: "pray-for-three", rtp: null, max_win: null, release_date: null, tagline: "Three is the magic number! All it takes is three lucky symbols to change your fortune forever. Get on your knees and pray for three.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Danny Dollar", slug: "danny-dollar", rtp: null, max_win: null, release_date: null, tagline: "Meet Danny Dollar — the most cash-obsessed character in the slots universe. He's rolling in it, and he wants to share.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Rad Maxx", slug: "rad-maxx", rtp: null, max_win: null, release_date: null, tagline: "Radical to the MAXX! Rad Maxx is the totally tubular slot cranking up the volume on wins.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Reign Of Rome", slug: "reign-of-rome", rtp: null, max_win: null, release_date: null, tagline: "All roads lead to Rome — and to riches! The Roman Empire is at its height and the spoils of conquest await.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Fighter Pit", slug: "fighter-pit", rtp: null, max_win: null, release_date: null, tagline: "The arena is ready, the crowd is roaring, and the prize money is waiting. Step into the Fighter Pit and battle for the championship purse.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Wishbringer", slug: "wishbringer", rtp: null, max_win: null, release_date: null, tagline: "The legendary Wishbringer has the power to grant any desire. Spin the reels, make your wish, and let the magic do the rest.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Life And Death", slug: "life-and-death", rtp: null, max_win: null, release_date: null, tagline: "In the timeless struggle between life and death, fortune favours the brave. Spin the reels of fate.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Dorks Of The Deep", slug: "dorks-of-the-deep", rtp: null, max_win: null, release_date: null, tagline: "Don't let their goofy looks fool you — the Dorks of the Deep are sitting on a treasure trove under the sea.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Strength Of Hercules", slug: "strength-of-hercules", rtp: null, max_win: null, release_date: null, tagline: "With the strength of a god behind every spin, the labours of fortune are yours to conquer alongside the legendary Hercules.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Hounds Of Hell", slug: "hounds-of-hell", rtp: null, max_win: null, release_date: null, tagline: "The fearsome hounds of the underworld have been unleashed upon the reels. Run with the pack for infernal riches.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Frkn Bananas", slug: "frkn-bananas", rtp: null, max_win: null, release_date: null, tagline: "This game is FRKN BANANAS! A fruit-fuelled frenzy where the wilds go wild and the bonuses go even wilder.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Marlin Masters", slug: "marlin-masters", rtp: null, max_win: null, release_date: null, tagline: "Master the open seas! The Marlin Masters are legendary anglers chasing the greatest catch in the ocean.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Phoenix Duelreels", slug: "phoenix-duelreels", rtp: null, max_win: null, release_date: null, tagline: "Rise from the ashes and duel! The phoenix rises and the DuelReels spin in this mythical battle for fortune.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Le Viking", slug: "le-viking", rtp: null, max_win: null, release_date: null, tagline: "The most daring Norse warrior has set sail for riches. Pillage the reels, plunder the bonuses, and sail home victorious.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Klowns", slug: "klowns", rtp: null, max_win: null, release_date: null, tagline: "These Klowns mean business! The big top has come to town — but these aren't ordinary clowns. They're here for your jackpot.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Fire My Laser", slug: "fire-my-laser", rtp: null, max_win: null, release_date: null, tagline: "In a sci-fi universe of lasers and neon, the trigger-happy hero is locked and loaded. Fire your laser at the reels.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Donut Division", slug: "donut-division", rtp: null, max_win: null, release_date: null, tagline: "Reporting for duty — and donuts! The Donut Division is on a mission to deliver wins with a side of sprinkles.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Shaolin Master", slug: "shaolin-master", rtp: null, max_win: null, release_date: null, tagline: "An ancient warrior of unparalleled skill has mastered both the martial arts and the reels. Follow the path of enlightenment.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Snow Slingers", slug: "snow-slingers", rtp: null, max_win: null, release_date: null, tagline: "The Snow Slingers are locked in the greatest snowball fight the world has ever seen. Sling your way to winter wins.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Duel At Dawn", slug: "duel-at-dawn", rtp: null, max_win: null, release_date: null, tagline: "As the first light breaks, two gunslingers face each other across the dusty street. Only one walks away with the prize.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Wings Of Horus", slug: "wings-of-horus", rtp: null, max_win: null, release_date: null, tagline: "Horus spreads his mighty wings over the Egyptian reels. Under his divine gaze, pharaonic treasures are yours to claim.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Rise Of Ymir", slug: "rise-of-ymir", rtp: null, max_win: null, release_date: null, tagline: "From the ancient frost and fire of Norse mythology, the primordial giant Ymir rises to shake the world.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Get The Cheese", slug: "get-the-cheese", rtp: null, max_win: null, release_date: null, tagline: "In a world full of traps and obstacles, one brave mouse is on a mission to get the cheese. Navigate the reels — grab the prize!", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Cloud Princess", slug: "cloud-princess", rtp: null, max_win: null, release_date: null, tagline: "High above the world, the Cloud Princess reigns over a sky kingdom of incredible riches. Ascend to her realm.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Le Pharaoh", slug: "le-pharaoh", rtp: null, max_win: null, release_date: null, tagline: "Le Pharaoh commands the sands of time and the riches of the Nile. Enter his domain and discover the treasures buried beneath the pyramids.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Evil Eyes", slug: "evil-eyes", rtp: null, max_win: null, release_date: null, tagline: "Ancient and all-seeing, the Evil Eyes watch your every spin. Under their mysterious gaze, cursed gold and dark fortune await.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Octo Attack", slug: "octo-attack", rtp: null, max_win: null, release_date: null, tagline: "Eight arms, infinite wins! The mighty octopus has launched its attack on the reels, tentacles slapping wilds into place.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Donny Dough", slug: "donny-dough", rtp: null, max_win: null, release_date: null, tagline: "From humble beginnings to high-rolling wins — Donny Dough is the rags-to-riches story of the slot world.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Dragons Domain", slug: "dragons-domain", rtp: null, max_win: null, release_date: null, tagline: "In the darkest mountain, a fearsome dragon guards its hoard of gold. Brave the fire and claim what the dragon has been keeping from you.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Sixsixsix", slug: "sixsixsix", rtp: null, max_win: null, release_date: null, tagline: "666 is the most feared and fabled number in existence. Spin the number of the beast and unleash diabolical riches.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Tai The Toad", slug: "tai-the-toad", rtp: null, max_win: null, release_date: null, tagline: "Tai the Toad is small but mighty, hopping through lily pads and lucky symbols to bring you the biggest wins in the pond.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Twisted Lab", slug: "twisted-lab", rtp: null, max_win: null, release_date: null, tagline: "Deep in a secret underground facility, a deranged scientist is conducting experiments on the reels with explosive results.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Ze Zeus", slug: "ze-zeus", rtp: null, max_win: null, release_date: null, tagline: "Ze Zeus has spoken! The king of the gods descends from Mount Olympus to electrify the reels with divine jackpots.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Cursed Crypt", slug: "cursed-crypt", rtp: null, max_win: null, release_date: null, tagline: "An ancient burial chamber holds a terrible curse — and unimaginable treasure. Only those brave enough to spin can break the curse.", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Slayers Inc", slug: "slayers-inc", rtp: null, max_win: "15,000x", release_date: null, tagline: "Monster hunting is big business! Slayers Inc. is the most elite monster-slaying outfit in the world. Slay the beasts, collect the bounty.", volatility: "5/5", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Jelly Slice", slug: "jelly-slice", rtp: null, max_win: "10,000x", release_date: null, tagline: "Slice through the reels for sweet wins! Jelly Slice is the most deliciously satisfying slot around.", volatility: "3/5", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Keep Em", slug: "keep-em", rtp: null, max_win: "10,000x", release_date: null, tagline: "Keep Em if you've got em! Hold your winners, spin the rest, and build the ultimate winning combination.", volatility: "3/5", features: [], bonus_games: [], featured: false },
  { game_id: null, name: "Divine Drop", slug: "divine-drop", rtp: null, max_win: "10,000x", release_date: null, tagline: "The Divine is dropping in! Sacred symbols rain down from the heavens in a cascade of divine fortune.", volatility: "3/5", features: [], bonus_games: [], featured: false },

  // ── Pragmatic Play ────────────────────────────────────────────────────────
  // Popular (★)
  { pp: true, name: "Sweet Bonanza 2500", slug: "sweet-bonanza-2500", rtp: "96.52%", tagline: "Tumbling sweets, massive multipliers and wins up to 2,500× — the sweetest slot in the universe gets even bigger.", featured: true },
  { pp: true, name: "Sugar Rush Super Scatter", slug: "sugar-rush-super-scatter", rtp: "96.58%", tagline: "A candy-coated chaos of tumbling symbols and escalating multipliers. Sugar Rush Super Scatter turns every spin into a confectionery explosion.", featured: true },
  { pp: true, name: "Gates of Hades", slug: "gates-of-hades", rtp: "96.52%", tagline: "The gates of the underworld swing open — face Hades himself on a grid packed with multiplier wilds and divine fury.", featured: true },
  { pp: true, name: "Big Bass Bonanza 1000", slug: "big-bass-bonanza-1000", rtp: "96.51%", tagline: "The legendary fishing slot returns — cast your line for money fish worth up to 1,000× in the most famous bass hunt in slots.", featured: true },
  { pp: true, name: "Starlight Princess Super Scatter", slug: "starlight-princess-super-scatter", rtp: "96.50%", tagline: "An anime princess rules the starlit reels with scatter pays, glowing multipliers and Super Scatter mayhem.", featured: true },
  { pp: true, name: "5 Lions Megaways 2", slug: "5-lions-megaways-2", rtp: "96.50%", tagline: "Five majestic lions roar across Megaways reels in this electrifying sequel packed with free spins and multipliers.", featured: false },
  { pp: true, name: "5 Lions Reborn", slug: "5-lions-reborn", rtp: "96.50%", tagline: "The lions are reborn — reborn reels, reborn power, and the same legendary free spins that made the original iconic.", featured: false },
  { pp: true, name: "Bandit Megaways", slug: "bandit-megaways", rtp: "96.55%", tagline: "The Bandit is back with a Megaways engine. Up to 117,649 ways to win in this high-variance outlaw adventure.", featured: false },
  { pp: true, name: "Big Bass Bonanza 3 Reeler", slug: "big-bass-bonanza-3-reeler", rtp: "96.50%", tagline: "Three reels. One mission. Catch the biggest bass of your life in this stripped-back fishing classic.", featured: false },
  { pp: true, name: "Big Bass Boxing Bonus Round", slug: "big-bass-boxing-bonus-round", rtp: "96.50%", tagline: "The bass is lacing up its gloves — Big Bass Boxing combines fishy fortune with knockout bonus rounds.", featured: false },
  { pp: true, name: "Big Bass Christmas - Frozen Lake", slug: "big-bass-christmas-frozen-lake", rtp: "96.07%", tagline: "Ice fishing with festive flair — drill through the Frozen Lake to uncover Christmas bass worth big prizes.", featured: false },
  { pp: true, name: "Big Bass Football Bonanza", slug: "big-bass-football-bonanza", rtp: "96.50%", tagline: "Football and fishing collide in the ultimate sports mashup. Score goals and reel in money fish for a bonanza payout.", featured: false },
  { pp: true, name: "Big Bass Halloween 3", slug: "big-bass-halloween-3", rtp: "96.50%", tagline: "The bass gets spooky for Halloween — three rounds of haunted fishing, pumpkin wilds and monstrous money fish.", featured: false },
  { pp: true, name: "Big Bass Raceday Repeat", slug: "big-bass-raceday-repeat", rtp: "96.51%", tagline: "The races are on and the bass are running — Raceday Repeat brings retrigger-packed free spins to the track.", featured: false },
  { pp: true, name: "Big Bass Reel Repeat", slug: "big-bass-reel-repeat", rtp: "96.51%", tagline: "Reel it in, again and again — Reel Repeat's retriggering free spins keep the bass biting and the multipliers climbing.", featured: false },
  { pp: true, name: "Big Bass Return to the Races", slug: "big-bass-return-to-the-races", rtp: "96.07%", tagline: "The fish are back at the racetrack — collect money fish, trigger bonus rounds and race your way to big wins.", featured: false },
  { pp: true, name: "Big Bass Splash 1000", slug: "big-bass-splash-1000", rtp: "96.52%", tagline: "Make a splash for up to 1,000× — the Big Bass Splash series dives deeper with bigger money fish than ever.", featured: false },
  { pp: true, name: "Big Bass Trophy Catch", slug: "big-bass-trophy-catch", rtp: "96.50%", tagline: "Hunt the trophy bass — a legendary catch that could multiply your winnings beyond belief in this fan-favourite series.", featured: false },
  { pp: true, name: "Bigger Bass Splash", slug: "bigger-bass-splash", rtp: "96.50%", tagline: "Go bigger, splash harder — Bigger Bass Splash turns up the volume on multiplier money fish and bonus chaos.", featured: false },
  { pp: true, name: "Chilli Heat Spicy Spins", slug: "chilli-heat-spicy-spins", rtp: "96.58%", tagline: "Turn up the heat with Spicy Spins — blazing chilli wilds and scorching multipliers make every spin sizzle.", featured: false },
  { pp: true, name: "Fortune of Olympus", slug: "fortune-of-olympus", rtp: "96.55%", tagline: "The gods of Olympus bestow divine fortune — multiplier orbs, cluster wins and the power of the cosmos on every spin.", featured: false },
  { pp: true, name: "Joker's Jewels Cash", slug: "jokers-jewels-cash", rtp: "96.51%", tagline: "The classic Joker gets a Cash upgrade — jewel-studded reels with a cash collect mechanic for instant gem-powered prizes.", featured: false },
  { pp: true, name: "Joker's Jewels Hold & Spin", slug: "jokers-jewels-hold-spin", rtp: "96.52%", tagline: "Joker's Jewels meets Hold & Spin — lock your precious gems and spin for the full collection of dazzling cash prizes.", featured: false },
  { pp: true, name: "Mahjong Wins Super Scatter", slug: "mahjong-wins-super-scatter", rtp: "96.50%", tagline: "Ancient tiles meet modern wins — Mahjong Wins Super Scatter brings Eastern elegance to scatter-pays mayhem.", featured: false },
  { pp: true, name: "Sweet Bonanza Super Scatter", slug: "sweet-bonanza-super-scatter", rtp: "96.51%", tagline: "Sweet Bonanza reimagined with Super Scatter mechanics — land scatters anywhere and trigger multiplier-packed free spins.", featured: false },
  { pp: true, name: "The Big Dog House", slug: "the-big-dog-house", rtp: "96.53%", tagline: "The dogs are running the show — The Big Dog House brings canine chaos with sticky wilds and raining multipliers.", featured: false },
  { pp: true, name: "The Dog House - Royal Hunt", slug: "the-dog-house-royal-hunt", rtp: "96.50%", tagline: "The royal pack is on the hunt — sticky wilds, paw multipliers and a kennel full of bonus features await.", featured: false },
  { pp: true, name: "Wild West Gold Blazing Bounty", slug: "wild-west-gold-blazing-bounty", rtp: "96.48%", tagline: "The Wild West is ablaze with gold — ride into a blazing bounty of sticky wilds and money symbols.", featured: false },
  { pp: true, name: "Wolf Gold 4 Pack", slug: "wolf-gold-4-pack", rtp: "96.51%", tagline: "The wolf pack returns four times stronger — Wolf Gold 4 Pack multiplies the howling wins of the legendary original.", featured: false },
  { pp: true, name: "Zeus vs Hades - Gods of War 250", slug: "zeus-vs-hades-gods-of-war-250", rtp: "96.56%", tagline: "The ultimate divine duel — Zeus and Hades clash across 250 ways to win in this epic gods-of-war showdown.", featured: false },
  { pp: true, name: "Zombie School Megaways", slug: "zombie-school-megaways", rtp: "96.55%", tagline: "School's out — for the undead. Zombie School Megaways serves up horror-themed Megaways carnage with cascading reels.", featured: false },
  // Non-popular
  { pp: true, name: "3 Magic Eggs", slug: "3-magic-eggs", rtp: "96.51%", tagline: "Three enchanted eggs hold the secret to fortune — crack them open for magical multipliers and spellbound free spins.", featured: false },
  { pp: true, name: "777 Rush", slug: "777-rush", rtp: "96.50%", tagline: "Classic lucky sevens with a modern rush — fast-paced retro reels charged with electric wilds and rush multipliers.", featured: false },
  { pp: true, name: "Alien Invaders", slug: "alien-invaders", rtp: "96.50%", tagline: "The alien fleet has arrived — defend the reels or surrender to cosmic wins in this sci-fi invasion slot.", featured: false },
  { pp: true, name: "Anaconda Gold", slug: "anaconda-gold", rtp: "96.54%", tagline: "The golden anaconda coils around the reels — strike with expanding wilds and golden multipliers deep in the jungle.", featured: false },
  { pp: true, name: "Ancient Island Megaways", slug: "ancient-island-megaways", rtp: "96.55%", tagline: "A lost island of ancient civilisation unlocks Megaways fortune — cascading symbols and temple scatter wins await.", featured: false },
  { pp: true, name: "Argonauts", slug: "argonauts", rtp: "96.47%", tagline: "Join Jason and the Argonauts on their mythical quest for the Golden Fleece across the wine-dark seas.", featured: false },
  { pp: true, name: "Aztec Gems Megaways", slug: "aztec-gems-megaways", rtp: "96.58%", tagline: "The treasures of the Aztec empire glitter across Megaways reels — gem multipliers and temple bonuses await.", featured: false },
  { pp: true, name: "Aztec Smash", slug: "aztec-smash", rtp: "96.52%", tagline: "Smash through ancient Aztec stone for cascading riches — every tumble reveals more treasures from a lost civilisation.", featured: false },
  { pp: true, name: "Bee Keeper", slug: "bee-keeper", rtp: "96.51%", tagline: "Tend the hive and harvest honey wins — the Bee Keeper slots buzz with sticky wilds and sweet multipliers.", featured: false },
  { pp: true, name: "Bigger Barn House Bonanza", slug: "bigger-barn-house-bonanza", rtp: "96.50%", tagline: "The barn is bigger and the wins are bolder — Bigger Barn House Bonanza brings farm-fresh cascading riches.", featured: false },
  { pp: true, name: "Bingo Mania", slug: "bingo-mania", rtp: "96.51%", tagline: "Bingo meets slots in a manic collision of numbers, wilds and bonus balls that pay out in slot-style fashion.", featured: false },
  { pp: true, name: "Blitz Super Wheel", slug: "blitz-super-wheel", rtp: "96.52%", tagline: "Spin the Super Wheel at lightning speed — blitz through multiplier segments for instant jackpot-style prizes.", featured: false },
  { pp: true, name: "Bloody Dawn", slug: "bloody-dawn", rtp: "96.50%", tagline: "As dawn breaks red, dark forces stir — Bloody Dawn is a gothic horror slot of crimson wilds and cursed free spins.", featured: false },
  { pp: true, name: "Book of Monsters", slug: "book-of-monsters", rtp: "96.50%", tagline: "Open the forbidden Book of Monsters — each page reveals a terrifying expanding symbol and monstrous free spins.", featured: false },
  { pp: true, name: "Bounty Hunter", slug: "bounty-hunter", rtp: "96.51%", tagline: "Track down the most wanted outlaws in the west — Bounty Hunter rewards your pursuit with stacked wilds and cash prizes.", featured: false },
  { pp: true, name: "Brick House Bonanza", slug: "brick-house-bonanza", rtp: "96.50%", tagline: "Build your way to fortune brick by brick — Brick House Bonanza rewards every layer with cascading multiplier wins.", featured: false },
  { pp: true, name: "Caishen's Cash Pots", slug: "caishens-cash-pots", rtp: "96.49%", tagline: "The Chinese god of prosperity fills his golden pots — Caishen's Cash Pots overflows with Hold & Spin riches.", featured: false },
  { pp: true, name: "Candy Rush", slug: "candy-rush", rtp: "96.58%", tagline: "Rush through a world of pure sugar — Candy Rush delivers tumbling sweet symbols and cascading multiplier madness.", featured: false },
  { pp: true, name: "Captain Kraken Megaways", slug: "captain-kraken-megaways", rtp: "96.55%", tagline: "The legendary sea beast meets Megaways — Captain Kraken tentacles its way through up to 200,704 ways to win.", featured: false },
  { pp: true, name: "Cash Surge", slug: "cash-surge", rtp: "96.52%", tagline: "Cash is surging — a Hold & Spin mechanic floods the reels with money symbols for a tidal wave of prizes.", featured: false },
  { pp: true, name: "Chests of Cai Shen 2", slug: "chests-of-cai-shen-2", rtp: "96.50%", tagline: "Unlock the second chest of the prosperity god — more gold, more wilds and bigger jackpot prizes inside.", featured: false },
  { pp: true, name: "Club Tropicana - Happy Hour", slug: "club-tropicana-happy-hour", rtp: "96.50%", tagline: "It's always happy hour at Club Tropicana — cocktail wilds, neon multipliers and sun-soaked free spins all night.", featured: false },
  { pp: true, name: "Code of Cairo", slug: "code-of-cairo", rtp: "96.51%", tagline: "Crack the ancient code of Cairo — hieroglyph expanding symbols, scatter picks and Egyptian free spins await.", featured: false },
  { pp: true, name: "CULT", slug: "cult", rtp: "96.51%", tagline: "A darkly compelling slot with a cult following — mysterious symbols, ritual wilds and a devout free spins ceremony.", featured: false },
  { pp: true, name: "Cyberheist City", slug: "cyberheist-city", rtp: "96.50%", tagline: "Hack the neon city and pull off the ultimate digital heist — cyberpunk wilds and glitching multipliers await the bold.", featured: false },
  { pp: true, name: "Dino Drop", slug: "dino-drop", rtp: "96.47%", tagline: "Prehistoric giants drop onto the reels — Dino Drop crashes massive stacked symbols into cascading prize combos.", featured: false },
  { pp: true, name: "DJ Neko", slug: "dj-neko", rtp: "96.50%", tagline: "The cat DJ drops the beat — DJ Neko spins lucky symbols with rhythm-powered wilds and music-fuelled free spins.", featured: false },
  { pp: true, name: "Dragon King Hot Pots", slug: "dragon-king-hot-pots", rtp: "96.54%", tagline: "The Dragon King stirs his hot pots of fortune — Hold & Spin action with sizzling cash prizes inside every pot.", featured: false },
  { pp: true, name: "Dragon Pots Megaways", slug: "dragon-pots-megaways", rtp: "96.58%", tagline: "Dragon-guarded pots of gold across Megaways reels — fiery cascades and pot-filling bonuses fuel the fortune.", featured: false },
  { pp: true, name: "Dragon Tiger Fortunes", slug: "dragon-tiger-fortunes", rtp: "96.54%", tagline: "Ancient rivals Dragon and Tiger battle across the reels — their clash unleashes fortune multipliers and wilds.", featured: false },
  { pp: true, name: "Dragon's Gate - Bonus Choice", slug: "dragons-gate-bonus-choice", rtp: "96.50%", tagline: "Stand at the Dragon's Gate and choose your bonus path — each door leads to different free spins and multiplier power.", featured: false },
  { pp: true, name: "Duel of Night & Day", slug: "duel-of-night-day", rtp: "96.47%", tagline: "Light and darkness clash across split reels — the Duel of Night & Day awards double features and dual multipliers.", featured: false },
  { pp: true, name: "Emerald King - Wheel of Wealth", slug: "emerald-king-wheel-of-wealth", rtp: "96.53%", tagline: "The Emerald King spins his Wheel of Wealth — Irish charm, golden coins and a jackpot wheel of fortune.", featured: false },
  { pp: true, name: "Emotiwins", slug: "emotiwins", rtp: "96.50%", tagline: "Expressive emoji symbols pack big emotional reactions — Emotiwins turns feelings into wilds, multipliers and bonuses.", featured: false },
  { pp: true, name: "Escape the Pyramid - Fire & Ice", slug: "escape-the-pyramid-fire-ice", rtp: "96.50%", tagline: "Navigate blazing fire and frozen ice corridors inside an ancient pyramid to escape with its legendary treasure.", featured: false },
  { pp: true, name: "Eye of Spartacus", slug: "eye-of-spartacus", rtp: "96.42%", tagline: "The eye of the gladiator never blinks — Spartacus watches the arena with expanding wilds and battle-bonus spins.", featured: false },
  { pp: true, name: "Fiesta Fortune", slug: "fiesta-fortune", rtp: null, tagline: "The fiesta never stops — colourful Día de los Muertos symbols and festive multipliers light up every spin.", featured: false },
  { pp: true, name: "Finger Lick'n Free Spins", slug: "finger-lickn-free-spins", rtp: "96.55%", tagline: "So good you'll lick your fingers — stacked food symbols and finger-lick'n free spins make every reel delicious.", featured: false },
  { pp: true, name: "Fire Stampede 2", slug: "fire-stampede-2", rtp: "96.51%", tagline: "The blazing herd returns — Fire Stampede 2 thunders across the savannah with flaming wilds and stampede free spins.", featured: false },
  { pp: true, name: "Fire Stampede Ultimate", slug: "fire-stampede-ultimate", rtp: "96.45%", tagline: "The ultimate stampede has arrived — the fiercest, most volatile version of the beloved Fire Stampede series.", featured: false },
  { pp: true, name: "Floating Dragon - Year of the Snake", slug: "floating-dragon-year-of-the-snake", rtp: null, tagline: "In the Year of the Snake, the Floating Dragon soars — celestial multipliers and lunar wilds bless every spin.", featured: false },
  { pp: true, name: "Floating Dragon Wild Horses", slug: "floating-dragon-wild-horses", rtp: "96.50%", tagline: "Wild horses ride with the Floating Dragon across mystical Eastern reels packed with expanding wilds.", featured: false },
  { pp: true, name: "Fonzo's Feline Fortunes", slug: "fonzos-feline-fortunes", rtp: "96.52%", tagline: "Fonzo the lucky cat is loaded with feline fortune — paws of gold, cat wilds and purr-fect multiplier prizes.", featured: false },
  { pp: true, name: "Fortune of Aztec", slug: "fortune-of-aztec", rtp: "96.50%", tagline: "The Aztec civilisation built its empire on gold — Fortune of Aztec unearths temple treasures with tumbling riches.", featured: false },
  { pp: true, name: "Frightening Frankie", slug: "frightening-frankie", rtp: "96.53%", tagline: "Frankie's the most frightening thing on the reels — a monster of multipliers with electrifying free spins.", featured: false },
  { pp: true, name: "Gem Fire Fortune", slug: "gem-fire-fortune", rtp: "96.50%", tagline: "Gems forged in fire hold unimaginable fortune — blazing crystal symbols cascade for multiplied jewel prizes.", featured: false },
  { pp: true, name: "Gem Trio", slug: "gem-trio", rtp: "96.53%", tagline: "Three legendary gems align for triple the treasure — ruby, sapphire and emerald combine for gem-powered big wins.", featured: false },
  { pp: true, name: "Genie's Gem Bonanza", slug: "genies-gem-bonanza", rtp: "96.50%", tagline: "Your wish is the genie's command — wish for gems, wilds or multipliers in this magical gem bonanza slot.", featured: false },
  { pp: true, name: "Gold Party 2 - After Hours", slug: "gold-party-2-after-hours", rtp: "96.55%", tagline: "The gold party keeps going after hours — neon wilds, money rains and VIP multipliers light up the after-dark reels.", featured: false },
  { pp: true, name: "Great Ghosts!", slug: "great-ghosts", rtp: "96.50%", tagline: "These ghosts are great — friendly spectres haunt the reels with ghostly wilds and spooky free spins galore.", featured: false },
  { pp: true, name: "Greedy Fortune Pig", slug: "greedy-fortune-pig", rtp: "96.50%", tagline: "The fortune pig can't stop collecting coins — Greedy Fortune Pig's Hold & Spin fills every cell with lucky cash.", featured: false },
  { pp: true, name: "Hammerstorm", slug: "hammerstorm", rtp: "96.50%", tagline: "A storm of hammer blows smashes the reels — Norse-inspired wilds crash down for thunderous multiplied wins.", featured: false },
  { pp: true, name: "Happy Dragon", slug: "happy-dragon", rtp: "96.50%", tagline: "The happiest dragon in the east dances across golden reels — joyful wilds and lucky scatters spread dragon fortune.", featured: false },
  { pp: true, name: "Happy Nets", slug: "happy-nets", rtp: "96.50%", tagline: "Cast your net wide and catch happiness — Happy Nets reels in stacked wilds and cascading net-full prize combos.", featured: false },
  { pp: true, name: "Haunted Crypt", slug: "haunted-crypt", rtp: "96.51%", tagline: "Deep in the haunted crypt, the dead stir — spine-chilling wilds and crypt scatter free spins guard the golden coffins.", featured: false },
  { pp: true, name: "Heartbreakers", slug: "heartbreakers", rtp: "96.53%", tagline: "Love can be dangerous — Heartbreakers deals out wild hearts, multiplier arrows and bonus rounds you won't forget.", featured: false },
  { pp: true, name: "Hot Tuna", slug: "hot-tuna", rtp: "96.53%", tagline: "This tuna is sizzling hot — ocean-fresh symbols, blazing wilds and a reel full of seared multiplier fish.", featured: false },
  { pp: true, name: "Hundreds and Thousands", slug: "hundreds-and-thousands", rtp: "96.52%", tagline: "Sprinkled with luck — Hundreds and Thousands showers colourful candy wins across tumbling reels.", featured: false },
  { pp: true, name: "Ice Mints", slug: "ice-mints", rtp: "96.50%", tagline: "Cool, crisp and refreshing — Ice Mints delivers icy wilds and frosty free spins in a minty-fresh slot experience.", featured: false },
  { pp: true, name: "Idol Pop Fever", slug: "idol-pop-fever", rtp: "96.50%", tagline: "The stage is yours — Idol Pop Fever brings K-pop energy with stage-time multipliers and fan-frenzy free spins.", featured: false },
  { pp: true, name: "Inca Queen", slug: "inca-queen", rtp: "96.55%", tagline: "The Inca Queen reigns over golden temples — ancient multipliers and royal free spins rule these South American reels.", featured: false },
  { pp: true, name: "Irish Crown", slug: "irish-crown", rtp: "96.52%", tagline: "The Crown of Ireland brings shamrock luck — four-leaf wilds, golden pots and rainbow multipliers for Irish fortune.", featured: false },
  { pp: true, name: "Jackpot Blaze", slug: "jackpot-blaze", rtp: "96.56%", tagline: "The jackpot is blazing — a fiery Hold & Spin mechanic heats up with every round until the infernal jackpot ignites.", featured: false },
  { pp: true, name: "Jelly Candy", slug: "jelly-candy", rtp: "96.52%", tagline: "Sweet, wobbly and full of prizes — Jelly Candy wobbles multiplier symbols into cascading sugar-coated wins.", featured: false },
  { pp: true, name: "Jelly Express", slug: "jelly-express", rtp: "96.50%", tagline: "All aboard the Jelly Express — this train of tumbling sweets rushes through multiplier stations on its way to big prizes.", featured: false },
  { pp: true, name: "John Hunter and Galileo's Secrets", slug: "john-hunter-and-galileos-secrets", rtp: "96.50%", tagline: "Explorer John Hunter uncovers the secrets of Galileo — astronomy-themed expanding symbols and constellation free spins.", featured: false },
  { pp: true, name: "Jumbo Safari", slug: "jumbo-safari", rtp: null, tagline: "A jumbo adventure across the African savannah — safari wildlife wilds and stampede free spins on every spin.", featured: false },
  { pp: true, name: "Knights vs Barbarians", slug: "knights-vs-barbarians", rtp: "96.51%", tagline: "An epic medieval clash — armoured knights and savage barbarians battle it out for war chest multipliers.", featured: false },
  { pp: true, name: "Launch to Riches", slug: "launch-to-riches", rtp: "96.52%", tagline: "3, 2, 1 — launch to riches! A rocket-fuelled space slot that blasts through multiplier orbits to stellar jackpots.", featured: false },
  { pp: true, name: "Lava Balls", slug: "lava-balls", rtp: "96.50%", tagline: "Volcanic lava balls roll across fiery reels — each eruption creates cascading molten multipliers in this hot slot.", featured: false },
  { pp: true, name: "Lobster House", slug: "lobster-house", rtp: "96.51%", tagline: "Crack open the lobster and find the treasure — seafood-stacked reels with a pinchy Hold & Spin mechanic.", featured: false },
  { pp: true, name: "Lucky Dice", slug: "lucky-dice", rtp: "96.53%", tagline: "Roll the lucky dice — every tumble reveals new multipliers in this high-stakes dice-meets-slot action.", featured: false },
  { pp: true, name: "Lucky Dog", slug: "lucky-dog", rtp: "96.50%", tagline: "Every dog has his day — and Lucky Dog's day involves stacked wilds, bone scatters and a jackpot-sized walkies.", featured: false },
  { pp: true, name: "Lucky Fortune Tree", slug: "lucky-fortune-tree", rtp: "96.50%", tagline: "Shake the Lucky Fortune Tree and watch golden coins fall — each branch holds a different multiplier treasure.", featured: false },
  { pp: true, name: "Lucky Monkey", slug: "lucky-monkey", rtp: "96.50%", tagline: "The luckiest monkey swings through golden reels — playful wilds and banana-powered scatters shower prizes.", featured: false },
  { pp: true, name: "Lucky Mouse", slug: "lucky-mouse", rtp: "96.57%", tagline: "The luckiest mouse in the world scurries across fortunate reels — tiny but mighty, with massive multiplier cheese.", featured: false },
  { pp: true, name: "Lucky Ox", slug: "lucky-ox", rtp: "96.55%", tagline: "The mighty ox brings strength and fortune — Lucky Ox charges through stacked wilds and prosperous free spins.", featured: false },
  { pp: true, name: "Lucky Panda", slug: "lucky-panda", rtp: "96.50%", tagline: "The bamboo-munching lucky panda rolls through golden reels — cuddly but loaded with wild fortune.", featured: false },
  { pp: true, name: "Lucky Phoenix", slug: "lucky-phoenix", rtp: "96.50%", tagline: "The Phoenix rises from ashes into blazing fortune — rebirth wilds and fire-scattered multipliers fill every spin.", featured: false },
  { pp: true, name: "Lucky Tiger", slug: "lucky-tiger", rtp: "96.50%", tagline: "The tiger is the luckiest predator — prowl through stacked wild symbols and pounce on tiger-powered jackpot wins.", featured: false },
  { pp: true, name: "Lucky Tiger 1000", slug: "lucky-tiger-1000", rtp: "96.50%", tagline: "The Lucky Tiger hunts for 1,000× — the most powerful predator in slots prowls for the ultimate jackpot.", featured: false },
  { pp: true, name: "Lucky Tiger Gold", slug: "lucky-tiger-gold", rtp: "96.50%", tagline: "Golden stripes and golden wins — Lucky Tiger Gold is the most luxurious tiger hunt in slot history.", featured: false },
  { pp: true, name: "Lucky's Wild Pub", slug: "luckys-wild-pub", rtp: "96.50%", tagline: "Pull up a stool at Lucky's Wild Pub — the bar where wilds flow as freely as the drinks and everyone wins.", featured: false },
  { pp: true, name: "Lucky's Wild Pub 2", slug: "luckys-wild-pub-2", rtp: "96.50%", tagline: "Last orders at Lucky's Wild Pub 2 — even wilder than the original with a double round of multiplier bonuses.", featured: false },
  { pp: true, name: "Majestic Express - Gold Run", slug: "majestic-express-gold-run", rtp: "96.50%", tagline: "The gold train is running — board the Majestic Express for a cross-country journey packed with golden multipliers.", featured: false },
  { pp: true, name: "Master Gems", slug: "master-gems", rtp: "96.46%", tagline: "Master the art of gems — precision cascades and jewel multipliers reward the most skilful gem collectors.", featured: false },
  { pp: true, name: "Mermaid's Treasure Trove", slug: "mermaids-treasure-trove", rtp: "96.54%", tagline: "Dive into the mermaid's hidden trove — ocean pearls, coral wilds and deep-sea multipliers fill every chest.", featured: false },
  { pp: true, name: "Mining Rush", slug: "mining-rush", rtp: "96.56%", tagline: "Strike it rich in the gold rush — dynamite wilds blast through rocky reels to uncover gleaming ore multipliers.", featured: false },
  { pp: true, name: "Money Stacks Megaways", slug: "money-stacks-megaways", rtp: "96.52%", tagline: "Stack your money across Megaways reels — cascading cash symbols tumble for an avalanche of stacked prizes.", featured: false },
  { pp: true, name: "Mr Null's Wicked Wares", slug: "mr-nulls-wicked-wares", rtp: "96.49%", tagline: "Shop at Mr Null's Wicked Wares for cursed multipliers, hexed wilds and a bonus aisle full of dark surprises.", featured: false },
  { pp: true, name: "Mummy's Jewels", slug: "mummys-jewels", rtp: "96.50%", tagline: "Unwrap the mummy and claim its jewels — ancient Egyptian gems, expanding wilds and sarcophagus free spins.", featured: false },
  { pp: true, name: "Mummy's Jewels 100", slug: "mummys-jewels-100", rtp: "96.50%", tagline: "100× the jewels of the mummy — a turbo-charged version loaded with 100-pay Egyptian gem mechanics.", featured: false },
  { pp: true, name: "Mystic Wishes", slug: "mystic-wishes", rtp: "96.50%", tagline: "Make your mystic wish and let the magic unfold — enchanted wilds and wish-granted multipliers deliver your fortune.", featured: false },
  { pp: true, name: "Olympus Wins", slug: "olympus-wins", rtp: "96.50%", tagline: "The gods of Olympus unite for divine wins — cluster pays and multiplier lightning bolts rain down from the mountain.", featured: false },
  { pp: true, name: "Oracle of Gold", slug: "oracle-of-gold", rtp: "96.55%", tagline: "Consult the Oracle of Gold — divine prophecies translate into multiplier wilds and golden free spin revelations.", featured: false },
  { pp: true, name: "Pandemic Rising", slug: "pandemic-rising", rtp: "96.51%", tagline: "The outbreak spreads across the reels — Pandemic Rising's viral multipliers infect every symbol for chain reaction wins.", featured: false },
  { pp: true, name: "Peppe's Pepperoni Pizza Plaza", slug: "peppes-pepperoni-pizza-plaza", rtp: "96.55%", tagline: "Order up at Peppe's — the pizzeria where every slice is a wild, every topping is a multiplier and free spins are on the house.", featured: false },
  { pp: true, name: "Pig Farm", slug: "pig-farm", rtp: "96.00%", tagline: "Down on the pig farm, fortune grows — oink your way through muddy wilds and farm-fresh scatter bonuses.", featured: false },
  { pp: true, name: "Plushie Wins", slug: "plushie-wins", rtp: "96.84%", tagline: "The cutest slot ever made — Plushie Wins stuffs the reels with adorable toy wilds and the highest RTP on this page.", featured: false },
  { pp: true, name: "Raging Waterfall Megaways", slug: "raging-waterfall-megaways", rtp: "96.50%", tagline: "Cascade like a raging waterfall — Megaways power fuels an endless tumble of wins down the mountain's face.", featured: false },
  { pp: true, name: "Ratinho Sortudo", slug: "ratinho-sortudo", rtp: null, tagline: "The lucky little rat scurries through Brazilian fortune — colourful wilds and rodent luck power every spin.", featured: false },
  { pp: true, name: "Resurrecting Riches", slug: "resurrecting-riches", rtp: "96.50%", tagline: "From the grave come riches — Resurrecting Riches raises multiplied wins from the dead in this gothic bonus slot.", featured: false },
  { pp: true, name: "Ride The Lightning", slug: "ride-the-lightning", rtp: "96.50%", tagline: "Grab the lightning bolt and ride it to fortune — electric wilds and thunderbolt multipliers supercharge every spin.", featured: false },
  { pp: true, name: "Rolling in Treasures", slug: "rolling-in-treasures", rtp: "96.50%", tagline: "Roll, tumble and cascade your way to treasure — every drop reveals a new layer of multiplied prize potential.", featured: false },
  { pp: true, name: "Sanatorium Secrets", slug: "sanatorium-secrets", rtp: "96.47%", tagline: "The secrets of the abandoned sanatorium are yours to uncover — haunted wilds and asylum free spins tell a dark tale.", featured: false },
  { pp: true, name: "Santa's Slay", slug: "santas-slay", rtp: "96.53%", tagline: "Santa is on his sleigh and he's slaying — festive wilds, gift multipliers and a Christmas free spins massacre.", featured: false },
  { pp: true, name: "Savannah Legend", slug: "savannah-legend", rtp: "96.50%", tagline: "A legendary predator stalks the golden savannah — wildlife wilds and sunset scatter bonuses define this African epic.", featured: false },
  { pp: true, name: "Sleeping Dragon", slug: "sleeping-dragon", rtp: null, tagline: "The dragon sleeps but its gold does not — awaken expanding wilds and fire-scatter bonuses in this dormant giant.", featured: false },
  { pp: true, name: "Snow Party", slug: "snow-party", rtp: "96.50%", tagline: "The snow party never stops — icy wilds, snowflake scatters and a winter free spins festival for frosty big wins.", featured: false },
  { pp: true, name: "Spellmaster", slug: "spellmaster", rtp: "96.50%", tagline: "Master the ancient spells — each incantation transforms symbols into multiplied wilds in this arcane bonus slot.", featured: false },
  { pp: true, name: "Starlight Wins", slug: "starlight-wins", rtp: "96.50%", tagline: "Under a canopy of stars, fortune twinkles — Starlight Wins delivers constellation cluster pays and celestial multipliers.", featured: false },
  { pp: true, name: "Steamin' Reels", slug: "steamin-reels", rtp: "96.53%", tagline: "Full steam ahead — steampunk cogs, brass wilds and industrial multipliers drive this Victorian treasure machine.", featured: false },
  { pp: true, name: "Super Gummy Strike", slug: "super-gummy-strike", rtp: "96.47%", tagline: "Strike through layers of gummy candy for super wins — tumbling jelly symbols and strike multipliers deliver sweet chaos.", featured: false },
  { pp: true, name: "Super Tiki Strike", slug: "super-tiki-strike", rtp: "96.50%", tagline: "Island vibes and Tiki power collide — Super Tiki Strike brings tropical scatters and multiplied island wins.", featured: false },
  { pp: true, name: "Sweet Burst", slug: "sweet-burst", rtp: "96.50%", tagline: "The sweetness bursts in every direction — cascading candy wilds and burst multipliers send sugar wins flying.", featured: false },
  { pp: true, name: "Sweet Craze", slug: "sweet-craze", rtp: "97.54%", tagline: "The craziest sweet slot ever made with the highest RTP of the collection — 97.54% of sugary multiplied madness.", featured: false },
  { pp: true, name: "Sweet Rush Bonanza", slug: "sweet-rush-bonanza", rtp: "96.50%", tagline: "Rush through a bonanza of sweets — tumbling candy clusters and cascading multipliers create a non-stop sugar storm.", featured: false },
  { pp: true, name: "Temple Guardians", slug: "temple-guardians", rtp: "96.53%", tagline: "Ancient warriors guard a forgotten temple — awaken them with scatters for multiplied warrior free spins.", featured: false },
  { pp: true, name: "Touro Sortudo", slug: "touro-sortudo", rtp: null, tagline: "The lucky bull charges through Brazilian fortune with festive wilds and a bold Hold & Spin mechanic.", featured: false },
  { pp: true, name: "Treasures of Osiris", slug: "treasures-of-osiris", rtp: "96.52%", tagline: "Osiris guards the most sacred treasures of Egypt — unveil them with golden expanding wilds and pyramid free spins.", featured: false },
  { pp: true, name: "Triple Pot Diamond", slug: "triple-pot-diamond", rtp: "96.57%", tagline: "Three pots, one diamond, infinite fortune — Triple Pot Diamond fills every pot for a glittering jackpot-style climax.", featured: false },
  { pp: true, name: "Triple Pot Gold", slug: "triple-pot-gold", rtp: "96.02%", tagline: "Three golden pots overflow with classic Hold & Spin prizes — the original, the iconic, the timeless.", featured: false },
  { pp: true, name: "Triple Pot Plinko - Hercules", slug: "triple-pot-plinko-hercules", rtp: "96.55%", tagline: "Drop the ball with Hercules' strength — Plinko-style action fills three pots with Herculean multiplied prizes.", featured: false },
  { pp: true, name: "Tut's Treasure Tower", slug: "tuts-treasure-tower", rtp: "96.51%", tagline: "Climb Tutankhamun's treasure tower floor by floor — each level reveals more gold and more powerful free spins.", featured: false },
  { pp: true, name: "Volcano Goddess", slug: "volcano-goddess", rtp: "96.49%", tagline: "The Volcano Goddess commands fire and fortune — lava wilds and erupting multipliers flow from her island throne.", featured: false },
  { pp: true, name: "Waves of Poseidon", slug: "waves-of-poseidon", rtp: "96.55%", tagline: "The god of the seas unleashes crashing waves of fortune — Poseidon's trident splits reels for tidal multipliers.", featured: false },
  { pp: true, name: "Wealthy Frog", slug: "wealthy-frog", rtp: "96.50%", tagline: "The wealthiest frog in the pond hops through golden lily pads — each jump lands on a multiplied cash prize.", featured: false },
  { pp: true, name: "Wheel of Happiness", slug: "wheel-of-happiness", rtp: "96.47%", tagline: "Spin the Wheel of Happiness and land on joy — multipliers, free spins and jackpots share equal real estate.", featured: false },
  { pp: true, name: "Wild Skullz", slug: "wild-skullz", rtp: "96.44%", tagline: "Skull symbols stack for danger and reward — Wild Skullz is a bone-rattling slot of stacked wilds and skull scatters.", featured: false },
  { pp: true, name: "Wild Wild Joker", slug: "wild-wild-joker", rtp: "96.49%", tagline: "The wildest joker in the west — this outlaw joker multiplies every win and triggers the most chaotic free spins.", featured: false },
  { pp: true, name: "Wild Wild Pearls", slug: "wild-wild-pearls", rtp: "96.46%", tagline: "Pearl divers discover a ocean of wild wins — Wild Wild Pearls shines with lustrous multipliers and deep-sea bonuses.", featured: false },
  { pp: true, name: "Wild Wild Riches Returns", slug: "wild-wild-riches-returns", rtp: "96.50%", tagline: "The riches are back and wilder than ever — Irish wilds, coin collecting and Hold & Spin returns for more fortune.", featured: false },
  { pp: true, name: "Wild Wildebeest Wins", slug: "wild-wildebeest-wins", rtp: "96.45%", tagline: "The great wildebeest migration stampedes across the reels — herd wilds and savannah scatters thunder to big wins.", featured: false },
  { pp: true, name: "Wisdom of Athena 1000 Xmas", slug: "wisdom-of-athena-1000-xmas", rtp: "96.00%", tagline: "The goddess of wisdom brings a festive gift — 1,000× Christmas multipliers blessed by Athena's divine intel.", featured: false },
  { pp: true, name: "Witch Heart Megaways", slug: "witch-heart-megaways", rtp: null, tagline: "A witch's heart beats through Megaways reels — dark magic, potion wilds and hexed free spins across 117,649 ways.", featured: false },
  { pp: true, name: "You Can Piggy Bank On It", slug: "you-can-piggy-bank-on-it", rtp: "96.53%", tagline: "Smash the piggy bank for guaranteed fortune — every spin fills the pig with cash prizes ready to be collected.", featured: false },
  { pp: true, name: "Zeus vs Typhon", slug: "zeus-vs-typhon", rtp: "96.49%", tagline: "The king of the gods faces the mightiest monster — Zeus battles Typhon across lightning-charged multiplier reels.", featured: false },
];

// Enrich each slot with provider info, URLs, and tags
const SLOTS = RAW_SLOTS.map((s) => {
  if (s.pp) {
    // Pragmatic Play slot
    return {
      ...s,
      provider_id: "pragmatic",
      provider_name: "Pragmatic Play",
      provider_website: "https://www.pragmaticplay.com",
      hacksaw_url: `https://www.pragmaticplay.com/en/games/${s.slug}/`,
      thumbnail_url: null,
      logo_url: null,
      hero_url: null,
      features: [],
      bonus_games: [],
      bonus_buy_rtps: [],
      max_win: s.max_win || null,
      release_date: s.release_date || null,
      tags: getTags(s),
    };
  }
  // Hacksaw Gaming slot
  return {
    ...s,
    provider_id: "hacksaw",
    provider_name: "Hacksaw Gaming",
    provider_website: "https://www.hacksawgaming.com",
    hacksaw_url: `https://www.hacksawgaming.com/games/${s.slug}`,
    thumbnail_url: s.game_id
      ? `https://www-live.hacksawgaming.com/casino_thumbnails/${s.game_id}.jpg`
      : null,
    logo_url: s.game_id
      ? `https://www-live.hacksawgaming.com/casino_thumbnails/${s.game_id}_logo_Logo_800width.png`
      : null,
    hero_url: s.game_id
      ? `https://www-live.hacksawgaming.com/casino_thumbnails/${s.game_id}_hero_Devices_Desktop.png`
      : null,
    tags: getTags(s),
  };
});

// Search index — includes tag keywords for fuzzy theme matching (enables "rat" → "Get the Cheese")
function buildSearchIndex(slot) {
  const tagKeywords = TAG_RULES
    .filter(([tag]) => slot.tags.includes(tag))
    .flatMap(([, kws]) => kws)
    .join(" ");
  return [slot.name, slot.tagline, slot.tags.join(" "), tagKeywords]
    .join(" ")
    .toLowerCase();
}

SLOTS.forEach((s) => { s._searchIndex = buildSearchIndex(s); });

function searchSlots(query, providerFilter = null) {
  const q = query.trim().toLowerCase();
  let results = providerFilter
    ? SLOTS.filter((s) => s.provider_id === providerFilter)
    : SLOTS;
  if (!q) return results;
  return results.filter((s) => s._searchIndex.includes(q));
}

function getFeaturedSlots() {
  return SLOTS.filter((s) => s.featured);
}

function getSlotsByProvider(providerId) {
  return SLOTS.filter((s) => s.provider_id === providerId);
}
